<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="description" content="Company Details" />
    <meta name="keywords" content="Home Page, Oracle" />
    <meta name="author" content="Pallab Paul" />

    <title>Oracle INC</title>

    <!-- Favicon -->
    <link href="./images/favicon.ico" rel="icon" type="image/x-icon" />

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat%7CUbuntu"
      rel="stylesheet"
    />

    <!-- Font Awesome -->
    <script
      defer
      src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"
    ></script>

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
 
    <!-- CSS Applied -->
    <link rel="stylesheet" href="./styles/styles.css" />
    <link rel="stylesheet" href="./styles/backStyles.css" />
  </head>